# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 154cc30315390e0c8a32b5fc13fbed323ae65036773c06ccaf9fc3798cc097ef023eaf414a54995d3d626939cbf29d460d986d2f8467cdc5829988f9d6b544da
  database:
    :username: maridonnew
    :password: 1qaWSX3ed!@#
    
test:
  secret_key_base: f933cccf9042b51adc5fa242ea65e6f55c2045ba497001913ec7d37f4f8474899e369d5355ee2efa777d7ea0a0ae08e5ced9399836c3388839667fbd503eb4a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: c0fdf349cd63308d2af8141617d2b0918dd8139f6403041e17a9ffee52f360ae2bc8dac65ff6a5afdf05e50957325a46b78f0b64364f7ff81a4c552c95b6f392
  database:
    :username: maridonprod
    :password: 1qaWSX3ed!@#
  mailer:
    :username: postmaster@staging.lexiconresourcesonline.com
    :password: 411db8177f734d8eb97193d7dcfd0f62
    :domain: staging.lexiconresourcesonline.com
